name = "regenerated-dev"
type = "webpack"
routes = ["regenerated.dev/*", "www.regenerated.dev/*"]
zone_id = ""
kv_namespaces = []

[env.staging]
name = "regenerated-dev-staging"
route = "staging.regenerated.dev/*"
